# Generated by Django 3.0.8 on 2020-07-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
