# Generated by Django 3.2.4 on 2021-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_file',
            name='guest_email',
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='create_file',
            name='no_of_adults',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='create_file',
            name='no_of_children',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
