# Generated by Django 3.2.4 on 2021-07-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer_Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('PVT', 'Private Transfer'), ('SIC', 'Shared Transfer')], max_length=40)),
                ('vehicle', models.CharField(choices=[('MER E', 'Mercedes E Class or similar'), ('LUX', 'Mercedes S / BMW 5 or similar'), ('STD', 'Toyota Corola or similar'), ('MPV', 'VW Sharon or similar'), ('7SEAT', 'Ford Transporter or similar'), ('LUX7SEAT', 'Mercedes V Class or similar'), ('15SEAT', 'Mercedes Sprinter or similar'), ('49SEAT', 'SCANIA/Vanhool/Volvo Coach or similar'), ('54SEAT', 'SCANIA/Vanhool/Volvo Coach or similar')], max_length=40)),
                ('train_detail', models.CharField(blank=True, max_length=100)),
                ('pickup_date', models.DateTimeField()),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUP', 'Rs')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drop_off_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_transfer_train_related', related_query_name='operations_transfer_trains', to='products.accommodation')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_transfer_train_related', related_query_name='operations_transfer_trains', to='products.trainstation')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_transfer_train_related', related_query_name='operations_transfer_trains', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('PVT', 'Private Transfer'), ('SIC', 'Shared Transfer')], max_length=40)),
                ('vehicle', models.CharField(choices=[('MER E', 'Mercedes E Class or similar'), ('LUX', 'Mercedes S / BMW 5 or similar'), ('STD', 'Toyota Corola or similar'), ('MPV', 'VW Sharon or similar'), ('7SEAT', 'Ford Transporter or similar'), ('LUX7SEAT', 'Mercedes V Class or similar'), ('15SEAT', 'Mercedes Sprinter or similar'), ('49SEAT', 'SCANIA/Vanhool/Volvo Coach or similar'), ('54SEAT', 'SCANIA/Vanhool/Volvo Coach or similar')], max_length=40)),
                ('flight_detail', models.CharField(blank=True, max_length=100)),
                ('pickup_date', models.DateTimeField()),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUP', 'Rs')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drop_off_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_transfer_airport_related', related_query_name='operations_transfer_airports', to='products.accommodation')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_transfer_airport_related', related_query_name='operations_transfer_airports', to='products.airport')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_transfer_airport_related', related_query_name='operations_transfer_airports', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Return_Transfer_Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('PVT', 'Private Transfer'), ('SIC', 'Shared Transfer')], max_length=40)),
                ('vehicle', models.CharField(choices=[('MER E', 'Mercedes E Class or similar'), ('LUX', 'Mercedes S / BMW 5 or similar'), ('STD', 'Toyota Corola or similar'), ('MPV', 'VW Sharon or similar'), ('7SEAT', 'Ford Transporter or similar'), ('LUX7SEAT', 'Mercedes V Class or similar'), ('15SEAT', 'Mercedes Sprinter or similar'), ('49SEAT', 'SCANIA/Vanhool/Volvo Coach or similar'), ('54SEAT', 'SCANIA/Vanhool/Volvo Coach or similar')], max_length=40)),
                ('pickup_date', models.DateTimeField()),
                ('train_detail', models.CharField(blank=True, max_length=100)),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUP', 'Rs')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drop_off_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_return_transfer_train_related', related_query_name='operations_return_transfer_trains', to='products.trainstation')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_return_transfer_train_related', related_query_name='operations_return_transfer_trains', to='products.accommodation')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_return_transfer_train_related', related_query_name='operations_return_transfer_trains', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Return_Transfer_Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('PVT', 'Private Transfer'), ('SIC', 'Shared Transfer')], max_length=40)),
                ('vehicle', models.CharField(choices=[('MER E', 'Mercedes E Class or similar'), ('LUX', 'Mercedes S / BMW 5 or similar'), ('STD', 'Toyota Corola or similar'), ('MPV', 'VW Sharon or similar'), ('7SEAT', 'Ford Transporter or similar'), ('LUX7SEAT', 'Mercedes V Class or similar'), ('15SEAT', 'Mercedes Sprinter or similar'), ('49SEAT', 'SCANIA/Vanhool/Volvo Coach or similar'), ('54SEAT', 'SCANIA/Vanhool/Volvo Coach or similar')], max_length=40)),
                ('pickup_date', models.DateTimeField()),
                ('flight_detail', models.CharField(blank=True, max_length=100)),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUP', 'Rs')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drop_off_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_return_transfer_airport_related', related_query_name='operations_return_transfer_airports', to='products.airport')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_return_transfer_airport_related', related_query_name='operations_return_transfer_airports', to='products.accommodation')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_return_transfer_airport_related', related_query_name='operations_return_transfer_airports', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_journey', models.DateTimeField()),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUP', 'Rs')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_ticket_related', related_query_name='operations_add_tickets', to='products.supplier')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_ticket_related', related_query_name='operations_add_tickets', to='products.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Misc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_service', models.DateTimeField()),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(max_length=3000)),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUP', 'Rs')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('misc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_misc_related', related_query_name='operations_add_miscs', to='products.misc')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_misc_related', related_query_name='operations_add_miscs', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BF', 'Breakfast'), ('LU', 'Lunch'), ('DN', 'Dinner'), ('GD', 'Gala Dinner'), ('SN', 'Dinner with Snacks')], max_length=20)),
                ('date_of_service', models.DateTimeField()),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUP', 'Rs')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_meal_related', related_query_name='operations_add_meals', to='products.supplier')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_meal_related', related_query_name='operations_add_meals', to='products.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Day_Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_tour', models.DateTimeField()),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUP', 'Rs')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_day_tour_related', related_query_name='operations_add_day_tours', to='products.daytour')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_day_tour_related', related_query_name='operations_add_day_tours', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateTimeField()),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUP', 'Rs')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_attraction_related', related_query_name='operations_add_attractions', to='products.attraction')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_attraction_related', related_query_name='operations_add_attractions', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room_type', models.CharField(choices=[('SIN', 'Standard Single Room'), ('SDL', 'Standard Double Room'), ('TWN', 'Standard Twin Room'), ('TRP', 'Standard Triple Room'), ('DSL', 'Deluxe Single Room'), ('DDL', 'Deluxe Double Room'), ('DTW', 'Deluxe Twin Room'), ('DTR', 'Deluxe Triple Room'), ('SSL', 'Superior Single Room'), ('SDL', 'Superior Double Room'), ('STW', 'Superior Twin Room'), ('STR', 'Superior Triple Room'), ('JNR', 'Junior Suite Room'), ('SUT', 'Suite Room'), ('ONE', 'One Bedroom'), ('TWO', 'Two Bedroom'), ('THR', 'Three Bedroom'), ('STD', 'Studio Apartment')], max_length=30)),
                ('no_of_rooms', models.PositiveSmallIntegerField()),
                ('board_basis', models.CharField(choices=[('RM', 'Room Only'), ('BB', 'Bed & Breakfast'), ('HB', 'Half Board Basis'), ('FB', 'Full Board Basis'), ('AI', 'All Inclusive')], max_length=30)),
                ('confirmation_number', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('RUP', 'Rs')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_accommodation_related', related_query_name='operations_add_accommodations', to='products.accommodation')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_add_accommodation_related', related_query_name='operations_add_accommodations', to='products.supplier')),
            ],
        ),
    ]
